### ISSUE TITLE
Library View Error

### ISSUE THREAD

**Issue by jpkmiller** [HTWG-App/htwg-app-front#13]
Bib View seems to have an error that causes it not to be displayed anymore.
Maybe I am wrong, but it seems to be missing.

Some results of the [API](https://webapi.affluences.com/api/timetable?token=wWAjgowjn7iD85&week_offset=0&index=0) are null. Maybe this could result in an error?
```json
{"today":"2022-01-03","range":"03/01 - 09/01","times":[null,null,null,null,null,null,null],"index":0,"localized_full_days":["Montag","Dienstag","Mittwoch","Donnerstag","Freitag","Samstag","Sonntag"],"localized_short_days":["Mo.","Di.","Mit.","Do.","Fr.","Sa.","So."],"localized_closed":"Geschlossen","localized_open_24_24":"24/24"}
```

**Comment by jpkmiller** [comment]
Could you take a look at it?

**Comment by marcfrederick** [comment]
I've opened a PR that will solve this issue. The Affluences API was sending `null` on days where the Library is closed instead if the usual `[<opens>, <closes>]` tuple.
